version: '3'

services:
  postgres:
    container_name: my-pg
    networks:
      - my_network
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: abc123

volumes:
  logvolume01: {}

networks:
  my_network:
    #external:
    #  name: my_network
